version: '3.8'

services:
  # Frontend Development
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=http://localhost:5000/api/v1
    depends_on:
      - server

  # Backend Development
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
      - server_data:/app/data
    environment:
      - DATABASE_URL=file:./data/dev.db
      - JWT_SECRET=dev-jwt-secret
      - JWT_REFRESH_SECRET=dev-refresh-secret
      - NODE_ENV=development
      - FRONTEND_URL=http://localhost:3000
    command: >
      sh -c "npx prisma migrate dev &&
             npx prisma db seed &&
             npm run dev"

volumes:
  server_data: